apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pvt-sucess
  namespace: test
spec: ## this is related to replication controller.
  replicas: 4
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: ## Here the pod definiton kept 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  ## This is related pod specifications
      containers:
      - name: testcontainer
        image: malleshdevops/devopsus-project:react-v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: devops-pvt-secret
