apiVersion: batch/v1 
kind: Job 
metadata:   
  name: kubernetes-job-example   
  labels:     
    jobgroup: jobexample 
spec:   
  template:     
    metadata:       
      name: kubejob       
      labels:         
        jobgroup: jobexample     
    spec:       
      containers:       
      - name: job-example      
        image: devopscube/kubernetes-job-demo:latest         
        args: ["30"]       
      restartPolicy: OnFailure
