apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-liveness-socket
  namespace: dev
spec: ## this is related to replication controller.
  replicas: 1
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: ## Here the pod definiton kept 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  ## This is related pod specifications
      containers:
      - name: nginx
        image: nginx:1.20.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 80
