apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-multicontainer
  namespace: test
spec: ## this is related to replication controller.
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - {key: tier, operator: In, values: [web]}
  template: ## Here the pod definiton kept 
    metadata:
      name: mytest
      namespace: dev
      labels:
        app: web
        tier: web
        env: dev
    spec:  ## This is related pod specifications
      containers:
      - name: testcontainer
        image: nginx:1.20.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 500Mi #2Gi
            cpu: 200m
      - name: testing
        image: httpd
        ports:
        - containerPort: 80
      - name: test
        image: jenkins/jenkins:lts
