apiVersion: v1
kind: Service
metadata:
  name: nginx-service-1
  namespace: dev
spec:
  type: ClusterIP
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 85  ## this is service port
      targetPort: 80 ## container port
