apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret-error-1
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: test-secret-1
      mountPath: "/tmp/test"
      readOnly: true
  volumes:
  - name: test-secret-1
    secret:
      secretName: devops-secret123
      optional: true
