---
apiVersion: v1
kind: Pod
metadata:
 name: mytest-never-1
 namespace: dev
spec:
  containers:
  - name: testcontainer
    image: nginx:1.17.2
    imagePullPolicy: Never
  nodeSelector:
    evn: dev
