apiVersion: v1
kind: Pod
metadata:
 name: mypod-cm-vol
spec:
  containers:
  - name: testcontainer
    image: nginx
    volumeMounts:
    - name: config-test
      mountPath: /tmp/config.properties
      subPath: config.properties
  volumes:
  - name: config-test
    configMap:
      name: devops-cm
