apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: test-secret
      mountPath: "/tmp/test"
      readOnly: true
  volumes:
  - name: test-secret
    secret:
      secretName: devops-secret
      optional: true
