apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-test
  namespace: test
spec:
  replicas: 5
  selector:
    tier: web
  template:
    metadata:
      name: mytest
      namespace: dev
      labels:
        tier: web
    spec:
      containers:
      - name: testcontainer
        image: nginx
