apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 85  ## this is service port
      targetPort: 8080 ## container port
      nodePort: 30007
